"use client";

import { useState } from "react";
import { AgentSwarmControlCenter } from "./AgentSwarmControlCenter";
import { AutonomousApplicationQueue } from "./AutonomousApplicationQueue";
import { MarketIntelligenceRadar } from "./MarketIntelligenceRadar";
import {
  AutoGeneratedApplicationPacket,
  AgentActivityLog,
} from "@/lib/ai/autonomous-agents";
import { CURRENT_MARKET_INTELLIGENCE } from "@/lib/market/intelligence";

const INITIAL_PACKETS: AutoGeneratedApplicationPacket[] = [
  {
    id: "pkt-101",
    companyName: "Stripe",
    roleTitle: "Staff Software Engineer, Global Infrastructure",
    matchScore: 95,
    jobUrl: "https://stripe.com/jobs",
    location: "Remote (US / Worldwide)",
    salaryEst: "$210,000 - $285,000 + Equity",
    tailoredBullets: [
      "Engineered resilient distributed messaging pipeline using Apache Kafka, processing 22,000 requests/sec with p99 latency < 45ms.",
      "Optimized PostgreSQL connection pooling and multi-index strategies, eliminating query timeouts under 300% sudden traffic spikes.",
      "Spearheaded architectural transition to stateless Kubernetes microservices, slashing annual compute footprint by $140,000.",
    ],
    tailoredCoverLetter: `Dear Stripe Infrastructure Hiring Team,\n\nI have followed Stripe's distributed reliability milestones closely. My background architecting multi-region failover systems and asynchronous Kafka event ingestion aligns directly with Stripe's 99.999% uptime commitments.\n\nI would welcome the opportunity to discuss how my hands-on background in database sharding and latency optimization can accelerate Stripe's core infrastructure initiatives.`,
    recruiterOutreachNote: `Hi there, noticed Stripe is expanding its global infrastructure team. I recently synthesized an application highlighting my experience scaling Kafka and PostgreSQL to 22k+ RPS. Would love to share the architecture breakdown!`,
    status: "ready_to_apply",
    createdAt: "10 mins ago",
  },
  {
    id: "pkt-102",
    companyName: "Datadog",
    roleTitle: "Senior Distributed Systems Engineer",
    matchScore: 92,
    jobUrl: "https://datadoghq.com/careers",
    location: "New York, NY (Hybrid / Remote)",
    salaryEst: "$185,000 - $250,000 + Equity",
    tailoredBullets: [
      "Designed and deployed low-overhead distributed tracing agents monitoring 500+ microservices in real time.",
      "Implemented Redis LRU caching clusters with consistent hashing, reducing cross-service network egress by 38%.",
    ],
    tailoredCoverLetter: `Dear Datadog Engineering Team,\n\nObservability at scale requires disciplined trade-offs between tracing precision and runtime overhead. Having engineered high-throughput telemetry pipelines handling billions of daily events, I am eager to contribute to Datadog's distributed core.`,
    recruiterOutreachNote: `Hi! Saw Datadog's open Senior Distributed Systems role. My background focuses on low-latency telemetry pipelines and cache architectures. Excited to connect!`,
    status: "ready_to_apply",
    createdAt: "25 mins ago",
  },
];

export function AutonomousAgentCockpit() {
  const [packets, setPackets] = useState<AutoGeneratedApplicationPacket[]>(INITIAL_PACKETS);
  const [isDispatching, setIsDispatching] = useState(false);
  const [activeTab, setActiveTab] = useState<"packets" | "market_radar">("packets");
  const [activityLogs, setActivityLogs] = useState<AgentActivityLog[]>([
    {
      id: "log-1",
      agentType: "hunter",
      agentName: "Hunter Agent",
      actionText: "Scanned 140,000+ live jobs and matched 2 high-affinity positions (95% & 92% match)",
      category: "match",
      timestamp: "10 mins ago",
    },
    {
      id: "log-2",
      agentType: "radar",
      agentName: "Market Radar",
      actionText: "Detected +84.5% salary surge in AI Agent Orchestration and Rust systems",
      category: "surge",
      timestamp: "25 mins ago",
    },
    {
      id: "log-3",
      agentType: "guardian",
      agentName: "ATS Guardian",
      actionText: "Verified resume format against Workday 2026 parser algorithms — 100% compliant",
      category: "security",
      timestamp: "1 hour ago",
    },
  ]);

  const handleDispatchSwarm = async () => {
    setIsDispatching(true);

    try {
      const res = await fetch("/api/agents/dispatch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ agentType: "hunter", targetRole: "Staff Software Engineer" }),
      });

      if (!res.ok) throw new Error("Dispatch failed");
      const json = await res.json();
      if (json.data?.newPackets && json.data.newPackets.length > 0) {
        setPackets((prev) => [...json.data.newPackets, ...prev]);
        setActivityLogs((prev) => [
          {
            id: `log-${Date.now()}`,
            agentType: "hunter",
            agentName: "Hunter Agent",
            actionText: json.data.summaryLog || "Completed autonomous job scan cycle.",
            category: "dispatch",
            timestamp: "Just now",
          },
          ...prev,
        ]);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsDispatching(false);
    }
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* 1. Agent Swarm Control Center */}
      <AgentSwarmControlCenter
        onDispatchSwarm={handleDispatchSwarm}
        isDispatching={isDispatching}
      />

      {/* 2. Secondary Tab Switcher */}
      <div className="flex items-center gap-2 border-b border-zinc-200 pb-2">
        <button
          onClick={() => setActiveTab("packets")}
          className={`touch-target px-4 py-2 text-xs font-black rounded-xl transition-all ${
            activeTab === "packets"
              ? "bg-black text-white"
              : "bg-white text-zinc-600 hover:text-black hover:bg-zinc-100"
          }`}
        >
          🎯 Auto-Generated Application Packets ({packets.length})
        </button>

        <button
          onClick={() => setActiveTab("market_radar")}
          className={`touch-target px-4 py-2 text-xs font-black rounded-xl transition-all ${
            activeTab === "market_radar"
              ? "bg-black text-white"
              : "bg-white text-zinc-600 hover:text-black hover:bg-zinc-100"
          }`}
        >
          📈 Market Hiring Radar & Salary Surges
        </button>
      </div>

      {/* 3. Active Tab Content */}
      {activeTab === "packets" ? (
        <AutonomousApplicationQueue packets={packets} />
      ) : (
        <MarketIntelligenceRadar data={CURRENT_MARKET_INTELLIGENCE} />
      )}

      {/* 4. Live Agent Activity Stream Log */}
      <div className="bg-white border border-zinc-200 rounded-3xl p-6 space-y-4 shadow-sm">
        <div className="flex items-center justify-between pb-3 border-b border-zinc-200">
          <h3 className="text-xs font-black uppercase tracking-wider text-black flex items-center gap-1.5">
            <span>📜</span> Live Autonomous Swarm Activity Log
          </h3>
          <span className="text-[10px] font-mono text-zinc-400">Background Daemon Active</span>
        </div>

        <div className="divide-y divide-zinc-100">
          {activityLogs.map((log) => (
            <div
              key={log.id}
              className="py-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs"
            >
              <div className="flex items-center gap-2">
                <span className="px-2 py-0.5 rounded-md bg-zinc-100 border border-zinc-200 text-[10px] font-bold text-black uppercase">
                  {log.agentName}
                </span>
                <span className="text-zinc-800 font-medium">{log.actionText}</span>
              </div>
              <span className="text-[10px] font-mono text-zinc-400 shrink-0">
                {log.timestamp}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
