"use client";

import { useState } from "react";
import { AutoGeneratedApplicationPacket } from "@/lib/ai/autonomous-agents";

interface AutonomousApplicationQueueProps {
  packets: AutoGeneratedApplicationPacket[];
}

export function AutonomousApplicationQueue({
  packets,
}: AutonomousApplicationQueueProps) {
  const [selectedPacket, setSelectedPacket] = useState<AutoGeneratedApplicationPacket | null>(
    packets[0] || null
  );
  const [copiedType, setCopiedType] = useState<string | null>(null);

  const copyToClipboard = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    setCopiedType(type);
    setTimeout(() => setCopiedType(null), 2000);
  };

  if (!packets || packets.length === 0) {
    return (
      <div className="bg-white border border-zinc-200 rounded-3xl p-8 text-center space-y-3">
        <span className="text-3xl">🎯</span>
        <h3 className="text-sm font-black text-black">No Application Packets in Queue</h3>
        <p className="text-xs text-zinc-500 max-w-sm mx-auto">
          Click "Trigger Immediate Swarm Scan" above to instruct Hunter Agent to generate high-match application packets.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white border border-zinc-200 rounded-3xl p-6 sm:p-8 space-y-6 shadow-sm">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-zinc-200">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-md bg-zinc-100 border border-zinc-300 text-[10px] font-black uppercase text-black">
              HUNTER AGENT OUTPUT
            </span>
            <span className="text-xs font-mono font-bold text-zinc-500">
              {packets.length} Packets Ready
            </span>
          </div>
          <h3 className="text-lg font-black text-black">
            Auto-Generated Tailored Application Packets
          </h3>
          <p className="text-xs text-zinc-600">
            Synthesized by Hunter Agent with 1-click tailored bullets, cover letters, and hiring manager outreach.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left List (5 cols) */}
        <div className="lg:col-span-5 space-y-3">
          {packets.map((pkt) => {
            const isSelected = selectedPacket?.id === pkt.id;
            return (
              <div
                key={pkt.id}
                onClick={() => setSelectedPacket(pkt)}
                className={`p-4 rounded-2xl border transition-all cursor-pointer space-y-2 shadow-xs ${
                  isSelected
                    ? "bg-black text-white border-black"
                    : "bg-zinc-50 hover:bg-zinc-100 text-zinc-900 border-zinc-200 hover:border-black"
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className={`text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md ${
                    isSelected ? "bg-zinc-800 text-white" : "bg-white text-zinc-800 border border-zinc-200"
                  }`}>
                    {pkt.companyName}
                  </span>
                  <span className={`text-xs font-black font-mono ${
                    isSelected ? "text-emerald-400" : "text-emerald-700"
                  }`}>
                    {pkt.matchScore}% Match
                  </span>
                </div>

                <div>
                  <h4 className="text-xs font-bold">{pkt.roleTitle}</h4>
                  <span className={`text-[10px] block ${isSelected ? "text-zinc-300" : "text-zinc-500"}`}>
                    {pkt.location} • {pkt.salaryEst}
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right Detail Pane (7 cols) */}
        {selectedPacket && (
          <div className="lg:col-span-7 bg-zinc-50 border border-zinc-200 rounded-3xl p-5 sm:p-6 space-y-5">
            <div className="flex items-center justify-between pb-3 border-b border-zinc-200">
              <div>
                <h4 className="text-sm font-black text-black">
                  {selectedPacket.companyName} — {selectedPacket.roleTitle}
                </h4>
                <span className="text-xs text-zinc-500 font-mono">
                  {selectedPacket.location} • {selectedPacket.salaryEst}
                </span>
              </div>

              <a
                href={selectedPacket.jobUrl}
                target="_blank"
                rel="noreferrer"
                className="touch-target px-3.5 py-1.5 bg-white hover:bg-zinc-100 text-black border border-zinc-300 rounded-xl text-xs font-bold transition-all shadow-xs flex items-center gap-1"
              >
                <span>View Job</span>
                <span>↗</span>
              </a>
            </div>

            {/* Tailored STAR Bullets */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-black uppercase tracking-wider text-black">
                  Tailored STAR Resume Bullets:
                </span>
                <button
                  onClick={() =>
                    copyToClipboard(selectedPacket.tailoredBullets.join("\n"), "bullets")
                  }
                  className="text-[10px] font-bold text-zinc-600 hover:text-black"
                >
                  {copiedType === "bullets" ? "✓ Copied" : "Copy Bullets"}
                </button>
              </div>
              <div className="p-3 bg-white border border-zinc-200 rounded-2xl space-y-2 text-xs">
                {selectedPacket.tailoredBullets.map((b, idx) => (
                  <div key={idx} className="flex items-start gap-2">
                    <span className="text-black font-black text-xs">•</span>
                    <p className="text-zinc-800 leading-relaxed">{b}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Tailored Cover Letter */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-black uppercase tracking-wider text-black">
                  Tailored Cover Letter:
                </span>
                <button
                  onClick={() =>
                    copyToClipboard(selectedPacket.tailoredCoverLetter, "cover")
                  }
                  className="text-[10px] font-bold text-zinc-600 hover:text-black"
                >
                  {copiedType === "cover" ? "✓ Copied" : "Copy Letter"}
                </button>
              </div>
              <div className="p-3.5 bg-white border border-zinc-200 rounded-2xl text-xs text-zinc-800 whitespace-pre-line leading-relaxed max-h-40 overflow-y-auto font-sans">
                {selectedPacket.tailoredCoverLetter}
              </div>
            </div>

            {/* Recruiter Outreach Note */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-black uppercase tracking-wider text-black">
                  1-Click LinkedIn Pitch to Hiring Manager:
                </span>
                <button
                  onClick={() =>
                    copyToClipboard(selectedPacket.recruiterOutreachNote, "outreach")
                  }
                  className="text-[10px] font-bold text-zinc-600 hover:text-black"
                >
                  {copiedType === "outreach" ? "✓ Copied" : "Copy Pitch"}
                </button>
              </div>
              <div className="p-3 bg-white border border-zinc-200 rounded-2xl text-xs text-zinc-800 leading-relaxed font-sans">
                "{selectedPacket.recruiterOutreachNote}"
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
